#Assignment 1 Machine Learning

## Diego Useche Reyes, 2020 10

## Librerias Usadas

In [4]:
import numpy as np

## Problema 2

In [5]:
# Arrays for the computations

TD = np.array([[2, 3, 0, 3, 7],[0, 5, 5, 0, 3],[5, 0, 7, 3, 3],[3, 1, 0, 9, 9],[0, 0, 7, 1, 3],[6, 9, 4, 6, 0]])
L = np.array([[5, 2, 3, 6, 4, 3]]).T
m , n = TD.shape
TD

array([[2, 3, 0, 3, 7],
       [0, 5, 5, 0, 3],
       [5, 0, 7, 3, 3],
       [3, 1, 0, 9, 9],
       [0, 0, 7, 1, 3],
       [6, 9, 4, 6, 0]])

In [6]:
# Problem 2(a)

S1 = TD.sum(axis=0).reshape((1,n))

# Joint Probability
M1 = (1/n)*(TD/S1)
print(M1.sum())
M1

1.0


array([[0.025     , 0.03333333, 0.        , 0.02727273, 0.056     ],
       [0.        , 0.05555556, 0.04347826, 0.        , 0.024     ],
       [0.0625    , 0.        , 0.06086957, 0.02727273, 0.024     ],
       [0.0375    , 0.01111111, 0.        , 0.08181818, 0.072     ],
       [0.        , 0.        , 0.06086957, 0.00909091, 0.024     ],
       [0.075     , 0.1       , 0.03478261, 0.05454545, 0.        ]])

In [7]:
# Problem 2(b)

# Probability P(T/D)
M2 = M1*n
M2

array([[0.125     , 0.16666667, 0.        , 0.13636364, 0.28      ],
       [0.        , 0.27777778, 0.2173913 , 0.        , 0.12      ],
       [0.3125    , 0.        , 0.30434783, 0.13636364, 0.12      ],
       [0.1875    , 0.05555556, 0.        , 0.40909091, 0.36      ],
       [0.        , 0.        , 0.30434783, 0.04545455, 0.12      ],
       [0.375     , 0.5       , 0.17391304, 0.27272727, 0.        ]])

In [8]:
# Problem 2(d)

# Probability P(D)
P_D = (1/n)*np.ones(n).reshape(1,n)
P_D

array([[0.2, 0.2, 0.2, 0.2, 0.2]])

In [9]:
# Problem 2(e)

# Probability P(T)
P_T = (M1.sum(axis=1)).reshape(m,1)
print(P_T.sum())
P_T
# 

1.0


array([[0.14160606],
       [0.12303382],
       [0.17464229],
       [0.20242929],
       [0.09396047],
       [0.26432806]])

In [10]:
# Problem 2(c)

# Probabilty P(D/T) Based on Bayes P(D/T) = P(T/D)*P(D)/P(T)
M3 = (M2*P_D)/P_T
print(M3.sum(axis=1).reshape((m,1)))
M3

[[1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]]


array([[0.17654612, 0.23539482, 0.        , 0.19259576, 0.3954633 ],
       [0.        , 0.45154704, 0.35338464, 0.        , 0.19506832],
       [0.35787437, 0.        , 0.34853851, 0.15616336, 0.13742376],
       [0.18524987, 0.05488885, 0.        , 0.40418153, 0.35567975],
       [0.        , 0.        , 0.64782097, 0.09675248, 0.25542655],
       [0.28373832, 0.37831776, 0.13158879, 0.20635514, 0.        ]])

In [11]:
# Problem 2(f)

# Expected value of l E[l], expected value of the lenght of the caracter for each document

E_l = (M2*L).sum(axis=0).reshape((1,n))
E_l

array([[3.8125    , 3.22222222, 3.08695652, 4.54545455, 4.64      ]])

In [12]:
# Problem 2(g)

# Variance of the lenght l var(l), for each document

L_c = np.ones((m,n))*L
Var_l = (np.power((L_c-E_l),2)*M2).sum(axis=0)
Var_l


array([1.52734375, 1.39506173, 0.51417769, 1.88429752, 1.9104    ])